Doing the dang thang

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,3 +20,113 @@ jobs:
       - persist_to_workspace:
           root: .
           paths: .
+  check_vulnerabilities:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/felinefolia-react
+    steps:
+      - attach_workspace:
+          at: ~/felinefolia-react
+      - run: yarn install
+      - run: |
+            if [ "${CIRCLE_BRANCH}" == "production" ]; then
+              yarn validate:dependencies
+            else
+              yarn validate:dependencies || true
+            fi
+  test_and_report:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/felinefolia-react
+    steps:
+      - attach_workspace:
+          at: ~/felinefolia-react
+      - run: yarn install
+      - run: CI=true yarn test:coverage
+      - run: yarn reportCoverage
+      - store_artifacts:
+          path: ./coverage/clover.xml
+          prefix: tests
+      - store_artifacts:
+          path: coverage
+          prefix: coverage
+      - store_test_results:
+          path: ./coverage/clover.xml
+  build:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/felinefolia-react
+    steps:
+      - attach_workspace:
+          at: ~/felinefolia-react
+      - run: yarn install
+      - run:
+          name: yarn build
+          command: |
+            if [ "${CIRCLE_BRANCH}" == "production" ]; then
+              CI=true PUBLIC_URL=https://felinefolia-react-production.now.sh yarn build
+            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
+              CI=true PUBLIC_URL=https://felinefolia-react-alpha.now.sh yarn build
+            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
+              CI=true PUBLIC_URL=https://felinefolia-react-beta.now.sh yarn build
+            else
+              echo "This failed miserably!"
+            fi
+      - persist_to_workspace:
+          root: .
+          paths: .
+  deployment:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/felinefolia-react
+    steps:
+      - attach_workspace:
+          at: ~/felinefolia-react
+      - run: yarn install
+      - run: sudo yarn global add now
+      - deploy:
+          name: Deploy & Alias.
+          command: |
+            if [ "${CIRCLE_BRANCH}" == "production" ]; then
+              now build -t ${NOW_TOKEN} -n=felinefolia-react --static
+              now -t ${NOW_TOKEN} alias felinefolia-react-production.now.sh
+            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
+              now build -t ${NOW_TOKEN} -n=felinefolia-react --static
+              now -t ${NOW_TOKEN} alias felinefolia-react-alpha.now.sh
+            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
+              now build -t ${NOW_TOKEN} -n=felinefolia-react --static
+              now -t ${NOW_TOKEN} alias felinefolia-react-beta.now.sh
+            else
+              echo "This failed miserably!"
+            fi
+workflows:
+  version: 2
+  test_build_deploy:
+    jobs:
+      - checkout_code
+      - check_vulnerabilities:
+          requires:
+            - checkout_code
+      - test_and_report:
+          requires:
+            - checkout_code
+      - build:
+          requires:
+            - checkout_code
+          filters:
+            branches:
+              only:
+                - development
+                - master
+                - production
+      - deployment:
+          requires:
+            - check_vulnerabilities
+            - test_and_report
+            - build
+          filters:
+            branches:
+              only:
+                - development
+                - master
+- production
